server:
  port: 9081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news-service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
  #  h2:
  #    console:
  #      enabled: true
  #      path: /database
  #      settings:
  #        web-allow-others: true
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
web:
  access-control-allow-origin: "*"
  access-control-allow-headers: "*"
  access-control-allow-methods: "OPTIONS, POST, GET, PATCH, DELETE"

reddit:
  host: https://old.reddit.com
  user-agent: "Reddit-Bot (by /u/guguskis)"
twitter:
  consumer-key: "YOUR_CONSUMER_KEY"
  consumer-secret: "YOUR_CONSUMER_SECRET"
  access-token: "YOUR_ACCESS_TOKEN"
  access-token-secret: "YOUR_ACCESS_TOKEN_SECRET"

scan:
  subreddits:
    - "ukraine"
    - "combatFootage"
    - "cryptocurrency"
    - "xrp"
    - "ripple"
  twitter-keywords:
    - "xrp"
    - "ripple"
  twitter-users:
    - "attorneyjeremy1"
logging:
  level:
    com.azure.ai.textanalytics: WARN
