openapi: "3.0.0"
info:
  title: News API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /news:
    get:
      summary: List all news
      operationId: listNews
      tags:
        - news
      parameters:
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/subChannels'
      responses:
        200:
          description: A list of news
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsPage'
components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          format: string
        url:
          type: string
          format: string
        created:
          type: string
          format: date-time
        subChannel:
          type: string
          format: string
        channel:
          $ref: '#/components/schemas/Channel'
        sentiment:
          $ref: '#/components/schemas/Sentiment'
    Channel:
      type: string
      enum:
        - REDDIT
        - TWITTER
    Sentiment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sentiment: # todo rename to value
          $ref: '#/components/schemas/SentimentType'
        scoreNegative:
          type: number
          format: double
        scorePositive:
          type: number
          format: double
        scoreNeutral:
          type: number
          format: double
    SentimentType:
      type: string
      enum:
        - POSITIVE
        - NEGATIVE
        - NEUTRAL
        - MIXED
    NewsPage:
      properties:
        nextPageToken:
          type: integer
        news:
          type: array
          items:
            $ref: '#/components/schemas/News'
  parameters:
    pageToken:
      name: pageToken
      in: query
      description: Page token
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    pageSize:
      name: pageSize
      in: query
      description: Page size
      required: false
      schema:
        type: integer
        format: int32
        default: 20
    subChannels:
      name: subChannels
      in: query
      description: Sub channels
      required: true
      schema:
        type: array
        items:
          type: string
        default:
          - ukraine
          - lithuania