openapi: "3.0.0"
info:
  title: News API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /news:
    get:
      summary: List all news
      operationId: listNews
      tags:
        - news
      parameters:
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/subChannels'
      responses:
        200:
          description: A list of news
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsPage'
    post:
      summary: Create news
      operationId: createNews
      tags:
        - news
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewsRequest'
            examples:
              createRedditNewsRequest:
                $ref: '#/components/examples/CreateRedditNewsRequest'
            # fixme - openapi-generator-maven-plugin results in [WARNING] Ignoring complex example on request body
            # or springdoc-openapi-ui is faulty
      responses:
        201:
          description: News created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
  /news/{id}:
    get:
      summary: Get news by id
      operationId: getNewsById
      tags:
        - news
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: News found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        404:
          description: News not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /news/channel/{channel}:
    get:
      summary: List news by channel
      operationId: listNewsByChannel
      tags:
        - news
      parameters:
        - $ref: '#/components/parameters/channel'
        - $ref: '#/components/parameters/subChannels'
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
      responses:
        200:
          description: A list of news
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsPage'

components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          format: string
        url:
          type: string
          format: string
        created:
          type: string
          format: date-time
        subChannel:
          type: string
          format: string
        channel:
          $ref: '#/components/schemas/Channel'
        sentiment:
          $ref: '#/components/schemas/Sentiment'
    Channel:
      type: string
      enum:
        - REDDIT
        - TWITTER
    Sentiment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sentiment: # todo rename to value
          $ref: '#/components/schemas/SentimentType'
        scoreNegative:
          type: number
          format: double
        scorePositive:
          type: number
          format: double
        scoreNeutral:
          type: number
          format: double
    SentimentType:
      type: string
      enum:
        - POSITIVE
        - NEGATIVE
        - NEUTRAL
        - MIXED
    NewsPage:
      properties:
        nextPageToken:
          type: integer
        news:
          type: array
          items:
            $ref: '#/components/schemas/News'
    CreateNewsRequest:
      properties:
        title:
          type: string
          format: string
        url:
          type: string
          format: string
        channel:
          $ref: '#/components/schemas/Channel'
        subChannel:
          type: string
          format: string
    Error:
      type: object
      properties:
        message:
          type: string
          format: string
  parameters:
    id:
      name: id
      in: path
      description: News id
      required: true
      schema:
        type: integer
        format: int64
    pageToken:
      name: pageToken
      in: query
      description: Page token
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    pageSize:
      name: pageSize
      in: query
      description: Page size
      required: false
      schema:
        type: integer
        format: int32
        default: 20
    channel:
      name: channel
      in: query
      description: Channel
      required: false
      schema:
        $ref: '#/components/schemas/Channel'
    subChannels:
      name: subChannels
      in: query
      description: Sub channels
      required: true
      schema:
        type: array
        items:
          type: string
        default:
          - europe
  examples:
    CreateRedditNewsRequest:
      summary: Create reddit news for europe subreddit
      value:
        title: 'Lithuania hopes to boost cooperation with Taiwan: visiting vice minister'
        url: 'https://www.reddit.com/r/europe/comments/gxzqjb/lithuania_hopes_to_boost_cooperation_with_taiwan/'
        channel: 'REDDIT'
        subChannel: 'europe'