/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package lt.liutikas.reddit.openapi.api;

import lt.liutikas.reddit.openapi.model.Channel;
import lt.liutikas.reddit.openapi.model.CreateNewsRequest;
import lt.liutikas.reddit.openapi.model.Error;
import lt.liutikas.reddit.openapi.model.News;
import lt.liutikas.reddit.openapi.model.NewsPage;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "news", description = "the news API")
public interface NewsApi {

    default NewsApiDelegate getDelegate() {
        return new NewsApiDelegate() {};
    }

    /**
     * POST /news : Create news
     *
     * @param createNewsRequest  (optional)
     * @return News created (status code 201)
     */
    @Operation(
        operationId = "createNews",
        summary = "Create news",
        tags = { "news" },
        responses = {
            @ApiResponse(responseCode = "201", description = "News created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = News.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/news",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<News> createNews(
        @Parameter(name = "CreateNewsRequest", description = "") @Valid @RequestBody(required = false) CreateNewsRequest createNewsRequest
    ) {
        return getDelegate().createNews(createNewsRequest);
    }


    /**
     * GET /news/{id} : Get news by id
     *
     * @param id News id (required)
     * @return News found (status code 200)
     *         or News not found (status code 404)
     */
    @Operation(
        operationId = "getNewsById",
        summary = "Get news by id",
        tags = { "news" },
        responses = {
            @ApiResponse(responseCode = "200", description = "News found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = News.class))
            }),
            @ApiResponse(responseCode = "404", description = "News not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/news/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<News> getNewsById(
        @Parameter(name = "id", description = "News id", required = true) @PathVariable("id") Long id
    ) {
        return getDelegate().getNewsById(id);
    }


    /**
     * GET /news : List all news
     *
     * @param subChannels Sub channels (required)
     * @param pageToken Page token (optional, default to 0)
     * @param pageSize Page size (optional, default to 20)
     * @return A list of news (status code 200)
     */
    @Operation(
        operationId = "listNews",
        summary = "List all news",
        tags = { "news" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of news", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NewsPage.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/news",
        produces = { "application/json" }
    )
    default ResponseEntity<NewsPage> listNews(
        @NotNull @Parameter(name = "subChannels", description = "Sub channels", required = true) @Valid @RequestParam(value = "subChannels", required = true, defaultValue = "europe,ukraine,combatFootage,lithuania") List<String> subChannels,
        @Parameter(name = "pageToken", description = "Page token") @Valid @RequestParam(value = "pageToken", required = false, defaultValue = "0") Integer pageToken,
        @Parameter(name = "pageSize", description = "Page size") @Valid @RequestParam(value = "pageSize", required = false, defaultValue = "20") Integer pageSize
    ) {
        return getDelegate().listNews(subChannels, pageToken, pageSize);
    }


    /**
     * GET /news/channel/{channel} : List news by channel
     *
     * @param subChannels Sub channels (required)
     * @param channel Channel (optional)
     * @param pageToken Page token (optional, default to 0)
     * @param pageSize Page size (optional, default to 20)
     * @return A list of news (status code 200)
     */
    @Operation(
        operationId = "listNewsByChannel",
        summary = "List news by channel",
        tags = { "news" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of news", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NewsPage.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/news/channel/{channel}",
        produces = { "application/json" }
    )
    default ResponseEntity<NewsPage> listNewsByChannel(
        @NotNull @Parameter(name = "subChannels", description = "Sub channels", required = true) @Valid @RequestParam(value = "subChannels", required = true, defaultValue = "europe,ukraine,combatFootage,lithuania") List<String> subChannels,
        @Parameter(name = "channel", description = "Channel") @Valid @RequestParam(value = "channel", required = false) Channel channel,
        @Parameter(name = "pageToken", description = "Page token") @Valid @RequestParam(value = "pageToken", required = false, defaultValue = "0") Integer pageToken,
        @Parameter(name = "pageSize", description = "Page size") @Valid @RequestParam(value = "pageSize", required = false, defaultValue = "20") Integer pageSize
    ) {
        return getDelegate().listNewsByChannel(subChannels, channel, pageToken, pageSize);
    }

}
